apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio-jenkins-backend
  template:
    metadata:
      labels:
        app: desafio-jenkins-backend
    spec:
      containers:
      - name: desafio-jenkins-backend
        image: rafaelldiass/pipedesafiojenkins:desafio-jenkins-backend{{tag}}
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: desafio-jenkins-service
spec:
  selector:
    app: desafio-jenkins
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30001
  type: NodePort