apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-jenkins-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio-jenkins-frontend
  template:
    metadata:
      labels:
        app: desafio-jenkins-frontend
    spec:
      containers:
      - name: desafio-jenkins-frontend
        image: rafaelldiass/pipedesafiojenkins:frontend-{{tag}}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: desafio-jenkins-frontend-service
spec:
  selector:
    app: desafio-jenkins-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
